import Link from 'next/link';

const sections = [
  ['1. Quem trata os dados', 'A G KONG opera a plataforma e trata os dados necessários à conta, segurança e funcionamento do serviço. O personal trainer é responsável pelas decisões profissionais e pelos dados de seus alunos que cadastra ou utiliza no acompanhamento. Cada parte deve cumprir suas obrigações conforme a atividade que realiza.'],
  ['2. Dados tratados', 'Podemos tratar nome, código protegido, dados profissionais do personal, configurações da conta, registros de acesso e segurança, fichas, execuções, agenda, mensagens, fotos e, quando informados, medidas, avaliações, lesões, restrições e outros dados de saúde. E-mail e telefone não são exigidos para autenticação.'],
  ['3. Finalidades e bases legais', 'Os dados são usados para autenticar usuários, entregar e registrar treinos, permitir acompanhamento, comunicação e suporte, prevenir fraude, manter a segurança e cumprir obrigações. O tratamento pode se apoiar na execução do serviço, consentimento — especialmente para dados sensíveis quando aplicável —, cumprimento legal e exercício regular de direitos. Não vendemos dados pessoais.'],
  ['4. Consentimento e dados opcionais', 'O personal declara possuir autorização para o cadastro inicial; isso não substitui a escolha do aluno. No primeiro acesso, o aluno confirma diretamente a Política e os Termos. Medidas e informações de saúde opcionais podem ser omitidas. O consentimento pode ser revogado, sem afetar tratamentos anteriores legítimos, mas algumas funções podem deixar de operar.'],
  ['5. Crianças e adolescentes', 'O serviço não deve ser usado por menor sem a participação e autorização de seu responsável legal e a observância das regras profissionais aplicáveis. O personal deve verificar essa condição antes do cadastro. O responsável pode exercer os direitos do titular pelos controles e canal indicados nesta Política.'],
  ['6. Compartilhamento', 'Os dados do aluno ficam acessíveis ao próprio aluno e ao personal responsável. Fornecedores de hospedagem, banco de dados, armazenamento, monitoramento e infraestrutura podem tratar o mínimo necessário para operar o serviço, sob obrigações de segurança e confidencialidade. Dados também podem ser compartilhados por obrigação legal ou para proteger direitos.'],
  ['7. Transferências e armazenamento', 'Fornecedores podem manter infraestrutura fora do Brasil. Nesses casos, adotamos mecanismos admitidos pela legislação aplicável e medidas contratuais e técnicas compatíveis com a proteção dos dados. Fotos de perfil enviadas ficam em armazenamento privado e são entregues por acesso autenticado.'],
  ['8. Segurança', 'Códigos são armazenados em formato irreversível; sessões podem ser revogadas; tentativas abusivas são limitadas; e dados privados são protegidos por controles de acesso. Nenhum sistema é imune a incidentes. Quando exigido, usuários e autoridades competentes serão comunicados de forma adequada.'],
  ['9. Retenção e exclusão', 'Mantemos dados enquanto a conta estiver ativa e pelo tempo necessário às finalidades, prevenção de fraude, cópias de segurança temporárias e obrigações legais. A exclusão integrada remove a conta e os dados vinculados do ambiente ativo, ressalvadas retenções obrigatórias ou necessárias ao exercício de direitos.'],
  ['10. Direitos do titular', 'Nos controles da conta, você pode corrigir informações, exportar uma cópia estruturada e solicitar exclusão. Também pode pedir confirmação de tratamento, acesso, correção, informação sobre compartilhamento, revisão quando aplicável, portabilidade nos limites regulamentares e revogação do consentimento.'],
  ['11. Canal de privacidade', 'Use Meu perfil ou Configurações para exportar, corrigir ou excluir dados. O aluno também pode solicitar apoio ao personal responsável pelo cadastro. Um canal dedicado para solicitações adicionais será informado nesta Política quando estiver disponível. Para proteger o titular, poderemos confirmar identidade e vínculo antes de atender ao pedido.'],
  ['12. Atualizações', 'Esta Política pode ser atualizada para refletir mudanças legais, técnicas ou do serviço. Alterações relevantes serão apresentadas na plataforma e, quando necessário, exigirão nova confirmação.'],
];

export default function PrivacyPage() {
  return <main className="min-h-screen bg-background px-4 py-12"><article className="mx-auto max-w-3xl space-y-8">
    <div><Link href="/" className="text-sm font-medium text-primary hover:underline">← Voltar ao início</Link><h1 className="mt-6 text-3xl font-bold">Política de Privacidade</h1><p className="mt-2 text-sm text-muted-foreground">Última atualização: 8 de agosto de 2026 · versão 2026-08-08</p></div>
    <p className="rounded-lg border bg-muted/20 p-4 leading-relaxed text-muted-foreground">Esta Política explica como a plataforma G KONG trata dados pessoais de personal trainers, alunos e responsáveis, em conformidade com a legislação brasileira de proteção de dados.</p>
    {sections.map(([title, text]) => <section key={title} className="space-y-3"><h2 className="text-xl font-semibold">{title}</h2><p className="leading-relaxed text-muted-foreground">{text}</p></section>)}
    <p className="text-sm text-muted-foreground">Consulte também os <Link href="/terms" className="text-primary underline">Termos de Uso</Link>.</p>
  </article></main>;
}
